#ifndef BLYNK_CONFIG_H
#define BLYNK_CONFIG_H

#define BLYNK_TEMPLATE_ID "TMPL5i2z9CRPw"
#define BLYNK_TEMPLATE_NAME "EASi"
#define BLYNK_AUTH_TOKEN "Iq2gtah4aNJB_ZyzkLsuoTblYGN4kIFu"

#endif // BLYNK_CONFIG_H